### ISSUE TITLE
ts typings error

### ISSUE THREAD

**Issue by n0mer** [tamino-martinius/node-ts-dedent#10]
Got error :

> error TS7016: Could not find a declaration file for module 'dedent'. '.../node_modules/dedent/dist/dedent.js' implicitly has an 'any' type.
>  Try `npm install @types/dedent` if it exists or add a new declaration (.d.ts) file containing `declare module 'dedent';`

Can you please publish `@types/ts-dedent`? That would help.

**Comment by tamino-martinius** [comment]
Typings are included
Defined here: https://github.com/tamino-martinius/node-ts-dedent/blob/master/package.json#L9
Shipped here: https://github.com/tamino-martinius/node-ts-dedent/blob/master/dist/index.d.ts

Can you add steps to reproduce or more details about your setup?
I close the issue until then

**Comment by n0mer** [comment]
@tamino-martinius would you consider publishing typings as separate package? For example, as https://www.npmjs.com/package/@types/node-ts-dedent
