### ISSUE TITLE
Unicode Escape Sequence Handling

### ISSUE THREAD

**Issue by ssaarela** [tamino-martinius/node-ts-dedent#34]
Feature request: unicode escape sequence handling.

```typescript
import dedent from 'dedent';

console.log(`\u00E4`); // Prints ä
console.log(dedent`\u00E4`); // Prints \u00E4 - expected ä
```

**Comment by ssaarela** [comment]
Some other escapes like `\r` are also not working as expected ATM. 

BTW, it's a very nice library! We're using it for testing a parser for a format where such special characters are present.

**Comment by bertho-zero** [comment]
The result is correct with the latest version:

![image](https://user-images.githubusercontent.com/8525267/197524767-1bfd1342-8233-4180-9517-3462fe842fa6.png)
[RunKit link](https://runkit.com/embed/xol8o8voxntg)

**Comment by ssaarela** [comment]
@bertho-zero That seems to be true! I thought I was using the latest, but following the README blindly I used `import dedent from 'dedent'` and the compiler says 
```
Could not find a declaration file for module 'dedent'. '.../node_modules/dedent/dist/dedent.js' implicitly has an 'any' type.
    Try `npm i --save-dev @types/dedent` if it exists or add a new declaration (.d.ts) file containing `declare module 'dedent';`
```
And following that error leads to verson 0.7.0 dedent instead of ts-dedent. With correct `import dedent from 'ts-dedent'` it works. 

Maybe README should be updated?

**Comment by tamino-martinius** [comment]
🤦 yes - readme seems to be wrong - will fix this

**Comment by tamino-martinius** [comment]
Addressed by https://github.com/tamino-martinius/node-ts-dedent/pull/35
